// ── Timezone → Country mapping ────────────────
// Shared between the dashboard and the transcripts page so country extraction
// stays consistent across the app.
//
// The base map is generated from the canonical IANA tz database (zone1970.tab
// + iso3166.tab): every primary "Region/City" zone maps to its country. The
// alias block below covers legacy/merged zones the IANA db consolidates into a
// neighbouring country's zone (e.g. Asia/Aden -> Yemen, not Saudi Arabia) plus
// the US/*, Canada/*, Australia/* shorthand forms. getCountryFromTimezone()
// then falls back to same-prefix inference for anything still unmapped.
export const TZ_TO_COUNTRY: Record<string, string> = {
  "Africa/Abidjan": "Ivory Coast",
  "Africa/Algiers": "Algeria",
  "Africa/Bissau": "Guinea-Bissau",
  "Africa/Cairo": "Egypt",
  "Africa/Casablanca": "Morocco",
  "Africa/Ceuta": "Spain",
  "Africa/El_Aaiun": "Western Sahara",
  "Africa/Johannesburg": "South Africa",
  "Africa/Juba": "South Sudan",
  "Africa/Khartoum": "Sudan",
  "Africa/Lagos": "Nigeria",
  "Africa/Maputo": "Mozambique",
  "Africa/Monrovia": "Liberia",
  "Africa/Nairobi": "Kenya",
  "Africa/Ndjamena": "Chad",
  "Africa/Sao_Tome": "Sao Tome and Principe",
  "Africa/Tripoli": "Libya",
  "Africa/Tunis": "Tunisia",
  "Africa/Windhoek": "Namibia",
  "America/Adak": "United States",
  "America/Anchorage": "United States",
  "America/Araguaina": "Brazil",
  "America/Argentina/Buenos_Aires": "Argentina",
  "America/Argentina/Catamarca": "Argentina",
  "America/Argentina/Cordoba": "Argentina",
  "America/Argentina/Jujuy": "Argentina",
  "America/Argentina/La_Rioja": "Argentina",
  "America/Argentina/Mendoza": "Argentina",
  "America/Argentina/Rio_Gallegos": "Argentina",
  "America/Argentina/Salta": "Argentina",
  "America/Argentina/San_Juan": "Argentina",
  "America/Argentina/San_Luis": "Argentina",
  "America/Argentina/Tucuman": "Argentina",
  "America/Argentina/Ushuaia": "Argentina",
  "America/Asuncion": "Paraguay",
  "America/Bahia": "Brazil",
  "America/Bahia_Banderas": "Mexico",
  "America/Barbados": "Barbados",
  "America/Belem": "Brazil",
  "America/Belize": "Belize",
  "America/Boa_Vista": "Brazil",
  "America/Bogota": "Colombia",
  "America/Boise": "United States",
  "America/Cambridge_Bay": "Canada",
  "America/Campo_Grande": "Brazil",
  "America/Cancun": "Mexico",
  "America/Caracas": "Venezuela",
  "America/Cayenne": "French Guiana",
  "America/Chicago": "United States",
  "America/Chihuahua": "Mexico",
  "America/Ciudad_Juarez": "Mexico",
  "America/Costa_Rica": "Costa Rica",
  "America/Coyhaique": "Chile",
  "America/Cuiaba": "Brazil",
  "America/Danmarkshavn": "Greenland",
  "America/Dawson": "Canada",
  "America/Dawson_Creek": "Canada",
  "America/Denver": "United States",
  "America/Detroit": "United States",
  "America/Edmonton": "Canada",
  "America/Eirunepe": "Brazil",
  "America/El_Salvador": "El Salvador",
  "America/Fort_Nelson": "Canada",
  "America/Fortaleza": "Brazil",
  "America/Glace_Bay": "Canada",
  "America/Goose_Bay": "Canada",
  "America/Grand_Turk": "Turks and Caicos Islands",
  "America/Guatemala": "Guatemala",
  "America/Guayaquil": "Ecuador",
  "America/Guyana": "Guyana",
  "America/Halifax": "Canada",
  "America/Havana": "Cuba",
  "America/Hermosillo": "Mexico",
  "America/Indiana/Indianapolis": "United States",
  "America/Indiana/Knox": "United States",
  "America/Indiana/Marengo": "United States",
  "America/Indiana/Petersburg": "United States",
  "America/Indiana/Tell_City": "United States",
  "America/Indiana/Vevay": "United States",
  "America/Indiana/Vincennes": "United States",
  "America/Indiana/Winamac": "United States",
  "America/Inuvik": "Canada",
  "America/Iqaluit": "Canada",
  "America/Jamaica": "Jamaica",
  "America/Juneau": "United States",
  "America/Kentucky/Louisville": "United States",
  "America/Kentucky/Monticello": "United States",
  "America/La_Paz": "Bolivia",
  "America/Lima": "Peru",
  "America/Los_Angeles": "United States",
  "America/Maceio": "Brazil",
  "America/Managua": "Nicaragua",
  "America/Manaus": "Brazil",
  "America/Martinique": "Martinique",
  "America/Matamoros": "Mexico",
  "America/Mazatlan": "Mexico",
  "America/Menominee": "United States",
  "America/Merida": "Mexico",
  "America/Metlakatla": "United States",
  "America/Mexico_City": "Mexico",
  "America/Miquelon": "St Pierre and Miquelon",
  "America/Moncton": "Canada",
  "America/Monterrey": "Mexico",
  "America/Montevideo": "Uruguay",
  "America/New_York": "United States",
  "America/Nome": "United States",
  "America/Noronha": "Brazil",
  "America/North_Dakota/Beulah": "United States",
  "America/North_Dakota/Center": "United States",
  "America/North_Dakota/New_Salem": "United States",
  "America/Nuuk": "Greenland",
  "America/Ojinaga": "Mexico",
  "America/Panama": "Panama",
  "America/Paramaribo": "Suriname",
  "America/Phoenix": "United States",
  "America/Port-au-Prince": "Haiti",
  "America/Porto_Velho": "Brazil",
  "America/Puerto_Rico": "Puerto Rico",
  "America/Punta_Arenas": "Chile",
  "America/Rankin_Inlet": "Canada",
  "America/Recife": "Brazil",
  "America/Regina": "Canada",
  "America/Resolute": "Canada",
  "America/Rio_Branco": "Brazil",
  "America/Santarem": "Brazil",
  "America/Santiago": "Chile",
  "America/Santo_Domingo": "Dominican Republic",
  "America/Sao_Paulo": "Brazil",
  "America/Scoresbysund": "Greenland",
  "America/Sitka": "United States",
  "America/St_Johns": "Canada",
  "America/Swift_Current": "Canada",
  "America/Tegucigalpa": "Honduras",
  "America/Thule": "Greenland",
  "America/Tijuana": "Mexico",
  "America/Toronto": "Canada",
  "America/Vancouver": "Canada",
  "America/Whitehorse": "Canada",
  "America/Winnipeg": "Canada",
  "America/Yakutat": "United States",
  "Antarctica/Casey": "Antarctica",
  "Antarctica/Davis": "Antarctica",
  "Antarctica/Macquarie": "Australia",
  "Antarctica/Mawson": "Antarctica",
  "Antarctica/Palmer": "Antarctica",
  "Antarctica/Rothera": "Antarctica",
  "Antarctica/Troll": "Antarctica",
  "Antarctica/Vostok": "Antarctica",
  "Asia/Almaty": "Kazakhstan",
  "Asia/Amman": "Jordan",
  "Asia/Anadyr": "Russia",
  "Asia/Aqtau": "Kazakhstan",
  "Asia/Aqtobe": "Kazakhstan",
  "Asia/Ashgabat": "Turkmenistan",
  "Asia/Atyrau": "Kazakhstan",
  "Asia/Baghdad": "Iraq",
  "Asia/Baku": "Azerbaijan",
  "Asia/Bangkok": "Thailand",
  "Asia/Barnaul": "Russia",
  "Asia/Beirut": "Lebanon",
  "Asia/Bishkek": "Kyrgyzstan",
  "Asia/Chita": "Russia",
  "Asia/Colombo": "Sri Lanka",
  "Asia/Damascus": "Syria",
  "Asia/Dhaka": "Bangladesh",
  "Asia/Dili": "East Timor",
  "Asia/Dubai": "United Arab Emirates",
  "Asia/Dushanbe": "Tajikistan",
  "Asia/Famagusta": "Cyprus",
  "Asia/Gaza": "Palestine",
  "Asia/Hebron": "Palestine",
  "Asia/Ho_Chi_Minh": "Vietnam",
  "Asia/Hong_Kong": "Hong Kong",
  "Asia/Hovd": "Mongolia",
  "Asia/Irkutsk": "Russia",
  "Asia/Jakarta": "Indonesia",
  "Asia/Jayapura": "Indonesia",
  "Asia/Jerusalem": "Israel",
  "Asia/Kabul": "Afghanistan",
  "Asia/Kamchatka": "Russia",
  "Asia/Karachi": "Pakistan",
  "Asia/Kathmandu": "Nepal",
  "Asia/Khandyga": "Russia",
  "Asia/Kolkata": "India",
  "Asia/Krasnoyarsk": "Russia",
  "Asia/Kuching": "Malaysia",
  "Asia/Macau": "Macau",
  "Asia/Magadan": "Russia",
  "Asia/Makassar": "Indonesia",
  "Asia/Manila": "Philippines",
  "Asia/Nicosia": "Cyprus",
  "Asia/Novokuznetsk": "Russia",
  "Asia/Novosibirsk": "Russia",
  "Asia/Omsk": "Russia",
  "Asia/Oral": "Kazakhstan",
  "Asia/Pontianak": "Indonesia",
  "Asia/Pyongyang": "North Korea",
  "Asia/Qatar": "Qatar",
  "Asia/Qostanay": "Kazakhstan",
  "Asia/Qyzylorda": "Kazakhstan",
  "Asia/Riyadh": "Saudi Arabia",
  "Asia/Sakhalin": "Russia",
  "Asia/Samarkand": "Uzbekistan",
  "Asia/Seoul": "South Korea",
  "Asia/Shanghai": "China",
  "Asia/Singapore": "Singapore",
  "Asia/Srednekolymsk": "Russia",
  "Asia/Taipei": "Taiwan",
  "Asia/Tashkent": "Uzbekistan",
  "Asia/Tbilisi": "Georgia",
  "Asia/Tehran": "Iran",
  "Asia/Thimphu": "Bhutan",
  "Asia/Tokyo": "Japan",
  "Asia/Tomsk": "Russia",
  "Asia/Ulaanbaatar": "Mongolia",
  "Asia/Urumqi": "China",
  "Asia/Ust-Nera": "Russia",
  "Asia/Vladivostok": "Russia",
  "Asia/Yakutsk": "Russia",
  "Asia/Yangon": "Myanmar",
  "Asia/Yekaterinburg": "Russia",
  "Asia/Yerevan": "Armenia",
  "Atlantic/Azores": "Portugal",
  "Atlantic/Bermuda": "Bermuda",
  "Atlantic/Canary": "Spain",
  "Atlantic/Cape_Verde": "Cape Verde",
  "Atlantic/Faroe": "Faroe Islands",
  "Atlantic/Madeira": "Portugal",
  "Atlantic/South_Georgia": "South Georgia & the South Sandwich Islands",
  "Atlantic/Stanley": "Falkland Islands",
  "Australia/Adelaide": "Australia",
  "Australia/Brisbane": "Australia",
  "Australia/Broken_Hill": "Australia",
  "Australia/Darwin": "Australia",
  "Australia/Eucla": "Australia",
  "Australia/Hobart": "Australia",
  "Australia/Lindeman": "Australia",
  "Australia/Lord_Howe": "Australia",
  "Australia/Melbourne": "Australia",
  "Australia/Perth": "Australia",
  "Australia/Sydney": "Australia",
  "Europe/Andorra": "Andorra",
  "Europe/Astrakhan": "Russia",
  "Europe/Athens": "Greece",
  "Europe/Belgrade": "Serbia",
  "Europe/Berlin": "Germany",
  "Europe/Brussels": "Belgium",
  "Europe/Bucharest": "Romania",
  "Europe/Budapest": "Hungary",
  "Europe/Chisinau": "Moldova",
  "Europe/Dublin": "Ireland",
  "Europe/Gibraltar": "Gibraltar",
  "Europe/Helsinki": "Finland",
  "Europe/Istanbul": "Turkey",
  "Europe/Kaliningrad": "Russia",
  "Europe/Kirov": "Russia",
  "Europe/Kyiv": "Ukraine",
  "Europe/Lisbon": "Portugal",
  "Europe/London": "United Kingdom",
  "Europe/Madrid": "Spain",
  "Europe/Malta": "Malta",
  "Europe/Minsk": "Belarus",
  "Europe/Moscow": "Russia",
  "Europe/Paris": "France",
  "Europe/Prague": "Czech Republic",
  "Europe/Riga": "Latvia",
  "Europe/Rome": "Italy",
  "Europe/Samara": "Russia",
  "Europe/Saratov": "Russia",
  "Europe/Simferopol": "Russia",
  "Europe/Sofia": "Bulgaria",
  "Europe/Tallinn": "Estonia",
  "Europe/Tirane": "Albania",
  "Europe/Ulyanovsk": "Russia",
  "Europe/Vienna": "Austria",
  "Europe/Vilnius": "Lithuania",
  "Europe/Volgograd": "Russia",
  "Europe/Warsaw": "Poland",
  "Europe/Zurich": "Switzerland",
  "Indian/Chagos": "British Indian Ocean Territory",
  "Indian/Maldives": "Maldives",
  "Indian/Mauritius": "Mauritius",
  "Pacific/Apia": "Samoa (western)",
  "Pacific/Auckland": "New Zealand",
  "Pacific/Bougainville": "Papua New Guinea",
  "Pacific/Chatham": "New Zealand",
  "Pacific/Easter": "Chile",
  "Pacific/Efate": "Vanuatu",
  "Pacific/Fakaofo": "Tokelau",
  "Pacific/Fiji": "Fiji",
  "Pacific/Galapagos": "Ecuador",
  "Pacific/Gambier": "French Polynesia",
  "Pacific/Guadalcanal": "Solomon Islands",
  "Pacific/Guam": "Guam",
  "Pacific/Honolulu": "United States",
  "Pacific/Kanton": "Kiribati",
  "Pacific/Kiritimati": "Kiribati",
  "Pacific/Kosrae": "Micronesia",
  "Pacific/Kwajalein": "Marshall Islands",
  "Pacific/Marquesas": "French Polynesia",
  "Pacific/Nauru": "Nauru",
  "Pacific/Niue": "Niue",
  "Pacific/Norfolk": "Norfolk Island",
  "Pacific/Noumea": "New Caledonia",
  "Pacific/Pago_Pago": "Samoa (American)",
  "Pacific/Palau": "Palau",
  "Pacific/Pitcairn": "Pitcairn",
  "Pacific/Port_Moresby": "Papua New Guinea",
  "Pacific/Rarotonga": "Cook Islands",
  "Pacific/Tahiti": "French Polynesia",
  "Pacific/Tarawa": "Kiribati",
  "Pacific/Tongatapu": "Tonga",
  // ── Legacy / merged / shorthand aliases ──
  "Africa/Accra": "Ghana",
  "Africa/Addis_Ababa": "Ethiopia",
  "Africa/Asmara": "Eritrea",
  "Africa/Bamako": "Mali",
  "Africa/Bangui": "Central African Republic",
  "Africa/Banjul": "Gambia",
  "Africa/Blantyre": "Malawi",
  "Africa/Brazzaville": "Congo",
  "Africa/Bujumbura": "Burundi",
  "Africa/Conakry": "Guinea",
  "Africa/Dakar": "Senegal",
  "Africa/Dar_es_Salaam": "Tanzania",
  "Africa/Djibouti": "Djibouti",
  "Africa/Douala": "Cameroon",
  "Africa/Freetown": "Sierra Leone",
  "Africa/Gaborone": "Botswana",
  "Africa/Harare": "Zimbabwe",
  "Africa/Kampala": "Uganda",
  "Africa/Kigali": "Rwanda",
  "Africa/Kinshasa": "DR Congo",
  "Africa/Libreville": "Gabon",
  "Africa/Libreville ": "Gabon",
  "Africa/Lome": "Togo",
  "Africa/Luanda": "Angola",
  "Africa/Lubumbashi": "DR Congo",
  "Africa/Lusaka": "Zambia",
  "Africa/Malabo": "Equatorial Guinea",
  "Africa/Maseru": "Lesotho",
  "Africa/Mbabane": "Eswatini",
  "Africa/Mogadishu": "Somalia",
  "Africa/Niamey": "Niger",
  "Africa/Nouakchott": "Mauritania",
  "Africa/Ouagadougou": "Burkina Faso",
  "Africa/Porto-Novo": "Benin",
  "America/Buenos_Aires": "Argentina",
  "America/Cordoba": "Argentina",
  "America/Indianapolis": "United States",
  "America/Knox_IN": "United States",
  "America/Louisville": "United States",
  "America/Mendoza": "Argentina",
  "America/Montreal": "Canada",
  "America/Nipigon": "Canada",
  "America/Thunder_Bay": "Canada",
  "Asia/Aden": "Yemen",
  "Asia/Bahrain": "Bahrain",
  "Asia/Calcutta": "India",
  "Asia/Chongqing": "China",
  "Asia/Dacca": "Bangladesh",
  "Asia/Harbin": "China",
  "Asia/Istanbul": "Turkey",
  "Asia/Kuala_Lumpur": "Malaysia",
  "Asia/Kuwait": "Kuwait",
  "Asia/Muscat": "Oman",
  "Asia/Phnom_Penh": "Cambodia",
  "Asia/Rangoon": "Myanmar",
  "Asia/Saigon": "Vietnam",
  "Asia/Tel_Aviv": "Israel",
  "Asia/Ujung_Pandang": "Indonesia",
  "Asia/Vientiane": "Laos",
  "Australia/ACT": "Australia",
  "Australia/Canberra": "Australia",
  "Australia/NSW": "Australia",
  "Australia/North": "Australia",
  "Australia/Queensland": "Australia",
  "Australia/South": "Australia",
  "Australia/Tasmania": "Australia",
  "Australia/Victoria": "Australia",
  "Australia/West": "Australia",
  "Canada/Atlantic": "Canada",
  "Canada/Central": "Canada",
  "Canada/Eastern": "Canada",
  "Canada/Mountain": "Canada",
  "Canada/Newfoundland": "Canada",
  "Canada/Pacific": "Canada",
  "Canada/Saskatchewan": "Canada",
  "Cuba": "Cuba",
  "Egypt": "Egypt",
  "Eire": "Ireland",
  "Europe/Amsterdam": "Netherlands",
  "Europe/Bratislava": "Slovakia",
  "Europe/Copenhagen": "Denmark",
  "Europe/Guernsey": "Guernsey",
  "Europe/Isle_of_Man": "Isle of Man",
  "Europe/Jersey": "Jersey",
  "Europe/Kiev": "Ukraine",
  "Europe/Ljubljana": "Slovenia",
  "Europe/Luxembourg": "Luxembourg",
  "Europe/Mariehamn": "Aland Islands",
  "Europe/Monaco": "Monaco",
  "Europe/Nicosia": "Cyprus",
  "Europe/Oslo": "Norway",
  "Europe/Podgorica": "Montenegro",
  "Europe/San_Marino": "San Marino",
  "Europe/Sarajevo": "Bosnia and Herzegovina",
  "Europe/Skopje": "North Macedonia",
  "Europe/Stockholm": "Sweden",
  "Europe/Uzhgorod": "Ukraine",
  "Europe/Vaduz": "Liechtenstein",
  "Europe/Vatican": "Vatican City",
  "Europe/Zagreb": "Croatia",
  "Europe/Zaporozhye": "Ukraine",
  "GB": "United Kingdom",
  "GB-Eire": "United Kingdom",
  "Hongkong": "Hong Kong",
  "Iran": "Iran",
  "Israel": "Israel",
  "Japan": "Japan",
  "NZ": "New Zealand",
  "PRC": "China",
  "Pacific/Midway": "Samoa (American)",
  "Pacific/Saipan": "Northern Mariana Islands",
  "ROC": "Taiwan",
  "ROK": "South Korea",
  "Singapore": "Singapore",
  "Turkey": "Turkey",
  "US/Alaska": "United States",
  "US/Arizona": "United States",
  "US/Central": "United States",
  "US/Eastern": "United States",
  "US/Hawaii": "United States",
  "US/Michigan": "United States",
  "US/Mountain": "United States",
  "US/Pacific": "United States",
  "US/Samoa": "Samoa (American)",
};

export function getCountryFromTimezone(tz: string | null): string {
  if (!tz) return "Unknown";
  if (TZ_TO_COUNTRY[tz]) return TZ_TO_COUNTRY[tz];

  // Fallback: infer from the region prefix when the exact zone is unmapped.
  // If any known zone shares the same continent prefix, the value is a real
  // place name we just don't have an entry for — surface it as-is rather than
  // "Unknown" so it can still be grouped/filtered.
  const slash = tz.indexOf("/");
  if (slash > 0) {
    const region = tz.slice(0, slash);
    const hasPrefix = Object.keys(TZ_TO_COUNTRY).some((k) => k.startsWith(region + "/"));
    if (hasPrefix) return tz;
  }
  return "Unknown";
}
